// Features with no visible control, or behind a right-click, a typed character, a hover or a switch.
// Copy ported from the approved mockup (round 12b, maket/index.html GUIDE); REHBER-KAYITLARI.md
// section 8 is generated from the same array. Edit the copy here, not in the guide code.
import { T, type GuideTopic } from '../types';

export const LESSER: GuideTopic[] = [
  {
    id: "slash", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Komutlar ve beceriler (/)", "Commands and skills (/)"),
    summary: T("/ yaz: modelin komutları ve beceriler listelenir.", "Type /: the model's commands and skills are listed."),
    keywords: T("slash komut beceri skill compact usage", "slash command skill compact usage"),
    steps: [
      { anchor: "composer-input", side: "above", align: "start", prepare: ["screen:chat"],
        title: T("Mesaj kutusuna / yaz", "Type / in the message box"),
        text: T("Komut ve beceri listesi açılır; seçtiğin yalnız kutuya yazılır, kendiliğinden gitmez. Liste seçili modele göre değişir; /compact ve /rehber hep vardır.", "A list of commands and skills opens; your pick only goes into the box, it is not sent. The list depends on the model; /compact and /guide are always there."),
      },
    ],
  },
  {
    id: "mention-mail", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Sohbetler arası not (@)", "Notes between chats (@)"),
    summary: T("Bir sohbet ötekine not bırakır; önce sana sorar.", "One chat leaves a note for another; it asks you first."),
    keywords: T("mention bahset not numara posta", "mention note number mailbox"),
    steps: [
      { anchor: "composer-input", side: "above", align: "start", prepare: ["screen:chat"],
        title: T("@ ile başka bir sohbet", "@ another chat"),
        text: T("@ yaz, bir sohbetin numarasını seç. Ona not bırakmamı isteyebilirsin; göndermeden önce onay kartı çıkar, o sohbet notu görünce kendiliğinden devam eder.", "Type @ and pick a chat by its number. Ask me to leave it a note; an approval card comes first, and that chat picks the note up on its own."),
      },
    ],
  },
  {
    id: "memory", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Hafızayı özetle", "Compact the memory"),
    summary: T("Hafıza göstergesi bir düğmedir: tıkla, sohbet özetlensin.", "The memory meter is a button: click it to compact the chat."),
    keywords: T("hafıza bağlam compact özet dolu", "memory context compact summary full"),
    steps: [
      { anchor: "strip-memory", side: "above", align: "center", prepare: ["screen:chat"],
        title: T("Hafıza dolunca", "When the memory fills up"),
        text: T("Bu gösterge sohbetin ne kadar dolduğunu söyler. Tıklarsan sohbeti özetleyip hafızaya alırım; /compact da aynısı. Uzun işlerde yer açar.", "This meter shows how full the chat is. Click it and I summarise the chat into memory; /compact does the same. It makes room on long jobs."),
      },
    ],
  },
  {
    id: "project-memory", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Proje hafızası", "Project memory"),
    summary: T("Projeni bir kez öğret; hafızayı dosya olarak taşı.", "Teach me your project once; carry the memory as a file."),
    keywords: T("öğren tara dışa aktar içe aktar md", "learn scan export import md"),
    steps: [
      { anchor: "strip-more", side: "above", align: "end", prepare: ["screen:chat"],
        title: T("Projeyi öğret", "Teach me the project"),
        text: T("Ekle ve sohbet menüsündeki Projeyi öğren projeni baştan tarar ve hafızaya yazar. Hafızayı .md dosyası olarak dışa aktarır, başka bir sohbete yüklersin.", "Learn project, in the Add & chat menu, scans the project and writes it to memory. Export the memory as an .md file and load it into another chat."),
      },
    ],
  },
  {
    id: "dictation", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Sesle yazma ve dil", "Dictation and language"),
    summary: T("Konuş, yazıya dökülsün; hangi dili konuştuğunu kendisi bulsun.", "Speak and it is typed; it can find your language by itself."),
    keywords: T("mikrofon ses konuş dil algıla", "microphone voice speak language detect"),
    steps: [
      { anchor: "composer-mic", side: "above", align: "end", prepare: ["screen:chat"],
        title: T("Sesle yaz", "Type by speaking"),
        text: T("Mikrofona bas, konuş, yeniden bas: yazıya döker, imlecin olduğu yere koyarım; kendiliğinden göndermem. Ses bilgisayarından çıkmaz. Esc vazgeçer.", "Press the mic, speak, press again: I type it where the cursor is and never send it by myself. The audio stays on your computer. Esc cancels."),
      },
      { anchor: "settings-dictation-lang", side: "below", align: "start", prepare: ["settings:general"],
        title: T("Hangi dilde konuşuyorsun", "Which language you speak"),
        text: T("Ekran kartı varsa dili kendim bulurum. Yoksa arayüz dilini dinlerim; başka dilde konuşacaksan bunu aç.", "With a graphics card I find the language myself. Without one I listen for the interface language; turn this on if you speak another."),
      },
    ],
  },
  {
    id: "video-url", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Videodan anlat", "Explain with a video"),
    summary: T("Bir video linki yapıştır; karelerine ve konuşmasına bakayım.", "Paste a video link; I look at its frames and speech."),
    keywords: T("youtube link url video yapıştır", "youtube link url video paste"),
    steps: [
      { anchor: "composer-input", side: "above", align: "start", prepare: ["screen:chat"],
        title: T("Video linki yapıştır", "Paste a video link"),
        text: T("YouTube, Vimeo, Loom ya da X'ten bir linki mesaja yapıştırırsan videodan kareler ve konuşmanın metnini çıkarıp ona bakarım. Bilgisayarındaki video için \"Ekle ve sohbet\" menüsünden Video'yu seç.", "Paste a YouTube, Vimeo, Loom or X link into the message and I pull frames and the spoken text from it. For a video on your computer, pick Video in the \"Add & chat\" menu."),
      },
    ],
  },
  {
    id: "queue", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Mesaj sırası", "The message queue"),
    summary: T("Ben çalışırken yazdığın mesaj sırada bekler.", "What you send while I work waits in line."),
    keywords: T("sıra bekle çalışırken", "queue wait while working"),
    steps: [
      { anchor: "composer-input", side: "above", align: "start", prepare: ["screen:chat"],
        title: T("Ben çalışırken yaz", "Write while I work"),
        text: T("Bir iş sürerken gönderdiğin mesaj sıraya girer. Sıradakini düzenler, silersin ya da hemen gönderirsin.", "A message you send while I work joins a queue. Edit it, remove it or send it right away."),
      },
    ],
  },
  {
    id: "background-wake", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Arkada biten iş", "Work that finishes in the background"),
    summary: T("Uzun iş arkada bitince sohbet kendiliğinden sürer.", "When a long job finishes, the chat carries on by itself."),
    keywords: T("arka plan devam bildirim", "background continue notification"),
    steps: [
      { anchor: "chat-running", side: "right", align: "start", prepare: ["screen:chat"],
        title: T("Kendiliğinden devam", "It carries on"),
        text: T("Arkada süren bir iş bitince sohbet kendiliğinden devam eder, üst üste en çok üç kez. Bitince ya da kart bekleyince bildirim gelir.", "When a job running in the background ends, the chat continues by itself, up to three times in a row. You get a notification when it is done or waits for a card."),
      },
    ],
  },
  {
    id: "file-chip", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Sohbetten panele", "From chat to panel"),
    summary: T("Sohbetteki dosya adı bir bağlantıdır.", "A file name in the chat is a link."),
    keywords: T("dosya bağlantı aç panelde", "file link open panel"),
    steps: [
      { anchor: "file-chip", side: "below", align: "start", prepare: ["screen:chat"],
        title: T("Dosya adına tıkla", "Click a file name"),
        text: T("Sohbette geçen bir dosya adı o dosyayı panelde açar. Araç satırındaki ve karttaki Ayrıntı da öyle.", "A file name in the chat opens that file in the panel. So do Details on a tool line and on a card."),
      },
    ],
  },
  {
    id: "file-tree", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Dosya ağacında sağ tık ve sürükle", "Right-click and drag in the file tree"),
    summary: T("Yeni dosya, taşıma, sohbete sürükleyip ekleme.", "New files, moving, dragging into the chat."),
    keywords: T("sağ tık menü yeniden adlandır sil taşı sürükle", "right click menu rename delete move drag"),
    steps: [
      { anchor: "file-tree", side: "left", align: "center", prepare: ["screen:chat", "workspace.tab:files"],
        title: T("Sağ tık ve sürükle", "Right-click and drag"),
        text: T("Sağ tık: yeni dosya, yeni klasör, yeniden adlandır, sil. Sürükleyerek taşırsın; mesaj kutusuna sürüklersen dosya içeriğiyle sohbete eklenir.", "Right-click: new file, new folder, rename, delete. Drag to move; drag onto the message box and the file goes into the chat with its contents."),
      },
    ],
  },
  {
    id: "auto-titles", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Otomatik sohbet adı", "Automatic chat titles"),
    summary: T("Sohbet kendi adını alır; senin verdiğin ada dokunmam.", "Chats name themselves; a name you gave stays."),
    keywords: T("ad başlık isim", "name title"),
    steps: [
      { anchor: "settings-auto-title", side: "below", align: "start", prepare: ["settings:general"],
        title: T("Sohbetin adı", "The chat's name"),
        text: T("İlk ve üçüncü cevaptan sonra sohbete konusunu anlatan bir ad koyarım; senin verdiğin ada dokunmam. Kapatmak istersen burada.", "After the first and the third reply I give the chat a name that says what it is about; I never touch a name you gave. Turn it off here."),
      },
    ],
  },
  {
    id: "shortcuts", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Klavye kısayolları", "Keyboard shortcuts"),
    summary: T("Enter, Ctrl N, Ctrl `, F1 ve birkaç tane daha.", "Enter, Ctrl N, Ctrl `, F1 and a few more."),
    keywords: T("kısayol tuş klavye f1 ctrl", "shortcut key keyboard f1 ctrl"),
    steps: [
      { anchor: "composer-send", side: "above", align: "end", prepare: ["screen:chat"],
        title: T("Yazarken", "While writing"),
        text: T("Enter gönderir (bu düğme gibi), Shift Enter yeni satır; üstüne gelince de yazar. Ctrl N yeni sohbet, Ctrl S açık dosyayı kaydeder.", "Enter sends (like this button), Shift Enter adds a line; hover it to see this again. Ctrl N is a new chat, Ctrl S saves the open file."),
      },
      { anchor: "ws-tabs", side: "left", align: "start",
        title: T("Panelde", "In the panel"),
        text: T("Ctrl ` alt çekmeceyi açıp kapatır, Ctrl Shift ` yeni terminal açar. ← → sekmeler arasında gezer.", "Ctrl ` opens and closes the bottom drawer, Ctrl Shift ` opens a new terminal. ← → moves between tabs."),
      },
      { anchor: "guide-entry", side: "right", align: "end",
        title: T("F1", "F1"),
        text: T("Bu rehberi açar. Mesaj kutusuna /rehber yazmak da aynısı.", "Opens this guide. Typing /guide in the message box does the same."),
      },
    ],
  },
  {
    id: "settings-search", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Ayarlarda arama", "Searching settings"),
    summary: T("Bir ayarı sayfa sayfa gezmeden bul.", "Find a setting without paging through."),
    keywords: T("ayar ara bul", "setting search find"),
    steps: [
      { anchor: "settings-search", side: "right", align: "start", prepare: ["settings:general"],
        title: T("Ayarlarda ara", "Search settings"),
        text: T("Ne aradığını yaz: “qr”, “ollama”, “yazı tipi”. Enter ilk sonucu açar.", "Type what you are after: “qr”, “ollama”, “font”. Enter opens the first match."),
      },
    ],
  },
  {
    id: "branches", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Sohbet dalları", "Chat branches"),
    summary: T("Asıl sohbeti bozmadan başka bir yol dene.", "Try another way without breaking the chat."),
    keywords: T("dal kopya fork sekme", "branch copy fork tab"),
    steps: [
      { anchor: "thread-actions", side: "below", align: "end", prepare: ["screen:chat"],
        title: T("Sohbeti dallandır", "Branch the chat"),
        text: T("Başlıktaki dal düğmesi bu sohbetin yazışmasını yeni bir dala kopyalar; asıl sohbet olduğu gibi kalır.", "The branch button in the header copies this chat's conversation into a new branch; the original stays as it is."),
      },
      { anchor: "branch-tabs", side: "below", align: "start",
        title: T("Dal sekmeleri", "Branch tabs"),
        text: T("Dallar sekme olur. Sağ tık: yeniden adlandır, kapat, sil. Kapattığın dal silinmez; Kapalı dallar'dan geri açarsın.", "Branches become tabs. Right-click: rename, close, delete. A closed branch is not deleted; reopen it from Closed branches."),
      },
    ],
  },
  {
    id: "side-chat", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Yan soru", "Side question"),
    summary: T("Ana işi bölmeden bir şey sor.", "Ask something without interrupting the main job."),
    keywords: T("yan sohbet soru salt okunur", "side chat question read-only"),
    steps: [
      { anchor: "thread-actions", side: "below", align: "end", prepare: ["screen:chat"],
        title: T("Yan soru", "Side question"),
        text: T("Ana iş sürerken bile sorabilirsin. Yan sohbet yalnız okur, dosyaya ve Unity'ye dokunmaz; istersen cevabı ana sohbete eklersin. Kapatınca silinir.", "Ask even while the main job runs. A side chat only reads and never touches files or Unity; add the answer to the main chat if you want. Closing it deletes it."),
      },
    ],
  },
  {
    id: "code-export", group: "lesser", since_version: "baseline", available_when: "always",
    title: T("Kodu Unity projesine yaz", "Write code into the Unity project"),
    summary: T("Kod bloğunu .cs dosyalarına bölüp projeye yazar.", "Splits a code block into .cs files and writes them to the project."),
    keywords: T("aktar export cs dosya script", "export cs file script"),
    steps: [
      { anchor: "code-block-actions", side: "below", align: "end", prepare: ["screen:chat"],
        title: T("Unity'ye aktar", "Export to Unity"),
        text: T("Kod bloğundaki bu düğme sınıfları ayrı .cs dosyalarına böler ve Assets/Scripts altına yazar; bir dosyanın üstüne yazacaksa önce uyarır.", "This button on a code block splits the classes into .cs files under Assets/Scripts, and warns before it overwrites a file."),
      },
    ],
  },
];
